### ISSUE TITLE
Edit cheesy muscle config to find a stable resting configuration

### ISSUE THREAD

**Issue by gurbain** [HBPNeurorobotics/mouse_locomotion#10]
At the moment, the cheesy muscle configuration (MouseDefConfig() ) only implements the back legs muscles and is however not stable...

The placement, and muscle parameters must be hand-tuned before moving to dynamical simulations exploring oscillator controlled muscles.

**Comment by drodarie** [comment]
This issue does not make sense anymore because we are working on stable configs for mouse and cheesy will probably be deprecated.
