### ISSUE TITLE
Isolate Blender processes

### ISSUE THREAD

**Issue by drodarie** [HBPNeurorobotics/mouse_locomotion#17]
As we might change our 3D simulator from Blender to SOFA, we have to isolate blender functions to be prepared for the switch.
Refactor the files and create static class to access Blender functions.

**Comment by drodarie** [comment]
Commits since 8ebcc71 isolate blender functions into package simulator and utils.
Files main.py and init.py still need to be refactor.

**Comment by gurbain** [comment]
Hep, I was looking at the Webots API in case we have to use it. It seems it is quite similar to the blender one, at least in its architecture. So if we can isolate those functions, the transition shouldn't be too difficult.

The only problem is that a license is only available for one single simulator, so it won't be easy to use the cloud without paying a lot..

**Comment by drodarie** [comment]
Last commit  dd27908 close this issue.
