### ISSUE TITLE
Wrong parsing during loading of file informations

### ISSUE THREAD

**Issue by drodarie** [HBPNeurorobotics/mouse_locomotion#19]
We store the results of the simulation in a file using pickle but the loading of these informations isn't parsed correctly : 
Info stored : 
{'body': {'muscles': [{'kc': 0, 'c': 100, 'logger': 'INFO', 'kl0': 0.8, 'name': 'muscle_neck1', 'obj_1': 'obj_body', 'obj_2': 'obj_head', 'k': 2000, 'anch_2': [-0.06, 0, -0.71], 'anch_1': [-0.95, 0, 0.47]},..]...}
Info loaded: 
{u'body': {u'muscles': [{u'kc': 0, u'c': 100, u'logger': u'INFO', u'kl0': 0.8, u'name': u'muscle_neck1', u'obj_1': u'obj_body', u'obj_2': u'obj_head', u'k': 2000, u'anch_2': [-0.06, 0, -0.71], u'anch_1': [-0.95, 0, 0.47]},..]...}

**Comment by gurbain** [comment]
Hep,

Where exactly is the problem? I it the u in front of each string?
http://stackoverflow.com/questions/2464959/whats-the-u-prefix-in-a-python-string

Gabriel

**Comment by drodarie** [comment]
I thought it was causing some bugs in the results but it was not, I fix my bugs in casting the result into a dictionary.
