### ISSUE TITLE
time.time() function working in Blender Game Engine?

### ISSUE THREAD

**Issue by gurbain** [HBPNeurorobotics/mouse_locomotion#5]
When a blender simulation is called, the blender game engine execute once the command _time.time()_ in _init.py_ and then at each time step in _main.py_ to test if the simulation time-out is reached.

However, this seems to provides unreliable results: time.time() in init.py is sometime ahead of the same command in main.py which terminate the simulations in advance

**Comment by drodarie** [comment]
Linked to a strange Blender's behavior in init.py line 58 :
owner["t_init"] = time.time() // In close launched simulations use the previous value, else use a round-like value of time.time() in the future or in the past.
owner["t_init"] = 1.234 // Work though

To avoid such bugs we should not use blender owner variable but python global variables.
