### ISSUE TITLE
Add a muscle_type parameter in config

### ISSUE THREAD

**Issue by drodarie** [HBPNeurorobotics/mouse_locomotion#7]
To choose the class of muscle you will use for the simulation, we should have a parameter in the Config class.

**Comment by gurbain** [comment]
I agree..

Do you think is is best to use this parameters in the body.py file? For instance:

```
class Backleg(Leg):
    """This class represents a generic backleg and its current behaviour in the control process"""

    def __init__(self, scene_, config_, orien_):
        """Class initialization"""

        Leg.__init__(self, scene_, config_)
        self.orien = orien_

        # Create the muscles objects following config
        if config_.muscle_type == "torque":
            do_something_here()
        elif config_.muscle_type == "spring":
           etc...
```

Or rather in muscle.py. For instance:

```
class Muscle(DampedSpringReducedTorqueMuscle):
    def __init__(self, scene_, params_):
        """Class initialization"""

       if params_.muscle_type == "torque":
           TorqueMuscle.__init__(self, scene_, params_)
        elif params_.muscle_type == "spring":
           DampedSpringReducedTorqueMuscle.__init__(self, scene_, params_)
```

I personally find the second solution clearer and more structured.

**Comment by gurbain** [comment]
Ah ok.. Like this it makes also sense. Even if I'm not a fan of eval functions except when they are inevitable.

**Comment by drodarie** [comment]
Yeah totally agree I'm not a big fan of this solution but I don't know how to properly allow the user to choose the muscle class from the config class. I'm not a fan of the "if else if" solution either...
